# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  scrivito:
    tenant: <%= ENV['SCRIVITO_TENANT'] %>
    api_key: <%= ENV['SCRIVITO_API_KEY'] %>
  secret_key_base: 2fac2cccfc38f8b8246a5e859f528b3291706404283ee1e487d8a21d55e59829909eec797b10a0ea07bd76ab8dc7514edf2b2ffeca6259c56d5b0341b54052cb

test:
  scrivito:
    tenant: <%= ENV['SCRIVITO_TENANT'] %>
    api_key: <%= ENV['SCRIVITO_API_KEY'] %>
  secret_key_base: 4bfef30d9a2c585947593012badb9a34f6496f5828eeffb06e41b25a6aa88b53aec949fe3b4bc6db985310454fb2afde38386b5a27cd34876561c7fb9999b2cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  scrivito:
    tenant: <%= ENV['SCRIVITO_TENANT'] %>
    api_key: <%= ENV['SCRIVITO_API_KEY'] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
